FROM jenkins/jenkins:lts
USER root

COPY ../../apache-maven-3.5.4 /usr/share/maven
RUN git config --global user.email "janardankelkar@gmail.com"
ENV PATH="/usr/share/maven/bin:${PATH}"

ENV MULE_HOME="/usr/share/mule/"
VOLUME ["${MULE_HOME}/logs", "${MULE_HOME}/conf", "${MULE_HOME}/apps", "${MULE_HOME}/domains"]
COPY ../../mule-enterprise-standalone-3.9.1 ${MULE_HOME}
